name = "neural-chronicles"
compatibility_date = "2026-03-14"
workers_dev = false

routes = [
	{ pattern = "neural-chronicles.uk", custom_domain = true },
	{ pattern = "www.neural-chronicles.uk", custom_domain = true }
]

[assets]
directory = "./app/dist"
not_found_handling = "single-page-application"
